// Typed access to the bundled corpus generated by scripts/build-corpus.mjs.
// The JSON ships inside the app bundle, so it is available offline with the
// shell; every item carries its SHA-256 so a stored trial can name its text.
import data from './corpus.json';

export interface CorpusItem {
  readonly id: string;
  readonly title: string;
  readonly file: string;
  readonly text: string;
  readonly chars: number;
  readonly sha256: string;
  readonly language?: string;
}

export interface TextCorpus {
  readonly id: string;
  readonly version: number;
  readonly kind: 'prose' | 'monthly' | 'symbols' | 'code';
  readonly textClass: string;
  readonly language: string;
  readonly license: string;
  readonly items: readonly CorpusItem[];
}

export interface WordCorpus {
  readonly id: string;
  readonly version: number;
  readonly kind: 'words';
  readonly language: string;
  readonly license: string;
  readonly beginnerCount: number;
  readonly words: readonly string[];
  readonly sha256: string;
}

interface CorpusFile {
  readonly formatVersion: number;
  readonly fingerprint: string;
  readonly prose: TextCorpus;
  readonly monthly: TextCorpus;
  readonly symbols: TextCorpus;
  readonly code: TextCorpus;
  readonly words: WordCorpus;
}

const corpus = data as unknown as CorpusFile;

export const CORPUS_FINGERPRINT = corpus.fingerprint;
export const PROSE: TextCorpus = corpus.prose;
export const MONTHLY: TextCorpus = corpus.monthly;
export const SYMBOLS: TextCorpus = corpus.symbols;
export const CODE: TextCorpus = corpus.code;
export const WORDS: WordCorpus = corpus.words;
export const BEGINNER_WORDS: readonly string[] = WORDS.words.slice(0, WORDS.beginnerCount);

export const MONTHLY_PASSAGE: CorpusItem = MONTHLY.items[0] as CorpusItem;

const ALL_TEXT: readonly TextCorpus[] = [PROSE, MONTHLY, SYMBOLS, CODE];

export function findItem(itemId: string): { corpus: TextCorpus; item: CorpusItem } | null {
  for (const c of ALL_TEXT) {
    const item = c.items.find((i) => i.id === itemId);
    if (item) return { corpus: c, item };
  }
  return null;
}

export function corpusById(id: string): TextCorpus | WordCorpus | null {
  if (id === WORDS.id) return WORDS;
  return ALL_TEXT.find((c) => c.id === id) ?? null;
}
